auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /var/lib/loki
  storage:
    s3:
      bucketnames: dl.logs.loki
      endpoint: s3.amazonaws.com
      region: us-west-2
      access_key_id: AKIASN6TRMFANQHTJNO3
      secret_access_key: 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
      s3forcepathstyle: true
      insecure: false
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
      alertmanager_url: http://localhost:9093