name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ID_CACHE_REDIS_HOST: ${{ secrets.AWS_ID_CACHE_REDIS_HOST }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run your build or deployment scripts
        run: |
          echo "Running some script..."
