export enum PurchaseUnit {
  bag = 'bag',
  bar = 'bar',
  block = 'block',
  bottle = 'bottle',
  box = 'box',
  bunch = 'bunch',
  can = 'can',
  carton = 'carton',
  clove = 'clove',
  container = 'container',
  cup = 'cup',
  dash = 'dash',
  dozen = 'dozen',
  drop = 'drop',
  drizzle = 'drizzle',
  fillet = 'fillet',
  fluidOunce = 'fluidOunce',
  gallon = 'gallon',
  gram = 'gram',
  head = 'head',
  kernel = 'kernel',
  kilogram = 'kilogram',
  leaf = 'leaf',
  liter = 'liter',
  loaf = 'loaf',
  milliliter = 'milliliter',
  packet = 'packet',
  pallet = 'pallet',
  pinch = 'pinch',
  pint = 'pint',
  pound = 'pound',
  quart = 'quart',
  rib = 'rib',
  sheet = 'sheet',
  single = 'single',
  slice = 'slice',
  sprig = 'sprig',
  sprinkle = 'sprinkle',
  stalk = 'stalk',
  stick = 'stick',
  strip = 'strip',
  tablespoon = 'tablespoon',
  teaspoon = 'teaspoon',
  weightOunce = 'weightOunce',
}

export enum States {
  // 50 state codes
  AL = 'AL',
  AK = 'AK',
  AZ = 'AZ',
  AR = 'AR',
  CA = 'CA',
  CO = 'CO',
  CT = 'CT',
  DE = 'DE',
  FL = 'FL',
  GA = 'GA',
  HI = 'HI',
  ID = 'ID',
  IL = 'IL',
  IN = 'IN',
  IA = 'IA',
  KS = 'KS',
  KY = 'KY',
  LA = 'LA',
  ME = 'ME',
  MD = 'MD',
  MA = 'MA',
  MI = 'MI',
  MN = 'MN',
  MS = 'MS',
  MO = 'MO',
  MT = 'MT',
  NE = 'NE',
  NV = 'NV',
  NH = 'NH',
  NJ = 'NJ',
  NM = 'NM',
  NY = 'NY',
  NC = 'NC',
  ND = 'ND',
  OH = 'OH',
  OK = 'OK',
  OR = 'OR',
  PA = 'PA',
  RI = 'RI',
  SC = 'SC',
  SD = 'SD',
  TN = 'TN',
  TX = 'TX',
  UT = 'UT',
  VT = 'VT',
  VA = 'VA',
  WA = 'WA',
  WV = 'WV',
  WI = 'WI',
  WY = 'WY',
}

export const worldCategories: string[] = [
  'African',
  'American',
  'Caribbean',
  'Chinese',
  'East European',
  'French',
  'Greek',
  'Indian',
  'Italian',
  'Japanese',
  'Korean',
  'Mediterranean',
  'Mexican',
  'Middle Eastern',
  'South American',
  'Spanish',
  'Thai',
  'Vietnamese',
];

export const notificationMethods: string[] = ['Enabled', 'None'];

export const darkModeOptions: string[] = [
  'Enabled',
  'Disabled',
  'System Default',
];
