//export a 'PurchaseUnit' enum with following:
//const unitEnum = ['gram', 'kilogram', 'ounce', 'pound', 'teaspoon', 'tablespoon', 'cup', 'pint', 'quart', 'gallon', 'milliliter', 'liter', 'bags', 'boxes', 'cartons', 'pallets', 'bottles', 'containers', 'bunch', 'dash', 'pinch', 'bar', 'stick', 'single', 'dozen'];

export enum PurchaseUnit {
  gram = 'gram',
  kilogram = 'kilogram',
  ounce = 'ounce',
  pound = 'pound',
  teaspoon = 'teaspoon',
  tablespoon = 'tablespoon',
  cup = 'cup',
  pint = 'pint',
  quart = 'quart',
  gallon = 'gallon',
  milliliter = 'milliliter',
  liter = 'liter',
  bag = 'bag',
  box = 'box',
  carton = 'carton',
  packet = 'packet',
  bottle = 'bottle',
  pallet = 'pallet',
  container = 'container',
  bunch = 'bunch',
  dash = 'dash',
  pinch = 'pinch',
  bar = 'bar',
  stick = 'stick',
  single = 'single',
  dozen = 'dozen',
}

export enum States {
  // 50 state codes
  AL = 'AL',
  AK = 'AK',
  AZ = 'AZ',
  AR = 'AR',
  CA = 'CA',
  CO = 'CO',
  CT = 'CT',
  DE = 'DE',
  FL = 'FL',
  GA = 'GA',
  HI = 'HI',
  ID = 'ID',
  IL = 'IL',
  IN = 'IN',
  IA = 'IA',
  KS = 'KS',
  KY = 'KY',
  LA = 'LA',
  ME = 'ME',
  MD = 'MD',
  MA = 'MA',
  MI = 'MI',
  MN = 'MN',
  MS = 'MS',
  MO = 'MO',
  MT = 'MT',
  NE = 'NE',
  NV = 'NV',
  NH = 'NH',
  NJ = 'NJ',
  NM = 'NM',
  NY = 'NY',
  NC = 'NC',
  ND = 'ND',
  OH = 'OH',
  OK = 'OK',
  OR = 'OR',
  PA = 'PA',
  RI = 'RI',
  SC = 'SC',
  SD = 'SD',
  TN = 'TN',
  TX = 'TX',
  UT = 'UT',
  VT = 'VT',
  VA = 'VA',
  WA = 'WA',
  WV = 'WV',
  WI = 'WI',
  WY = 'WY',
}
