const initialData = {
  friendships: {
    sequence: 1,
    data: [
      {
        friend: 'a525810e-5531-4f97-95a4-39a082f7416b',
      },
    ],
  },
  followships: {
    sequence: 2,
    data: [{ following: 'a525810e-5531-4f97-95a4-39a082f7416b' }, { following: 'ade96f70-4ec5-4ab9-adfe-0645b16e1ced' }],
  },
  ingredients: {
    sequence: 3,
    data: [
      {
        name: 'Butter',
        lifespanDays: 60,
        purchaseUnit: 'pound',
        gramRatio: 453.592,
        needsReview: false,
      },
      {
        name: 'Whole Milk',
        lifespanDays: 14,
        purchaseUnit: 'gallon',
        gramRatio: 3785.41,
        needsReview: false,
      },
    ],
  },
  tools: {
    sequence: 4,
    data: [
      {
        name: 'Cast Iron Skillet 12 Inch',
      },
      {
        name: 'Cutting Board 18x24 Inch',
      },
      {
        name: 'Mixing Spoon',
      },
      {
        name: 'Toaster Oven',
      },
      {
        name: 'Vegetable Peeler',
      },
    ],
  },
  recipes: {
    sequence: 5,
    data: [
      {
        sourceRecipeID: 0,
        title: 'Tiramisu',
        recipeCategoryID: 9,
        servings: 12,
        lifespanDays: 2,
        timePrep: 30,
        timeBake: 720,
        type: 'private',
        photoURL: 'https://s3.us-west-2.amazonaws.com/dl.images/recipe/a525810e-5531-4f97-95a4-39a082f7416b/tiramisu.jpg',
        ingredients: [
          {
            ingredientID: 0,
            name: 'Grand Marnier',
            lifespanDays: 300,
            purchaseUnit: 'liter',
            gramRatio: 950,
            purchaseUnitRatio: 0.015,
            measurementUnit: 'tablespoon',
            measurement: 6,
            preparation: '',
            component: 'Espresso Mixture',
          },
          {
            ingredientID: 0,
            name: 'Espresso',
            lifespanDays: 14,
            purchaseUnit: 'fluidOunce',
            gramRatio: 28,
            purchaseUnitRatio: 8,
            measurementUnit: 'cup',
            measurement: 1.25,
            preparation: '',
            component: 'Espresso Mixture',
          },
          {
            ingredientID: 0,
            name: 'Dark Rum',
            lifespanDays: 300,
            purchaseUnit: 'liter',
            gramRatio: 1001,
            purchaseUnitRatio: 0.236,
            measurementUnit: 'cup',
            measurement: 0.25,
            preparation: '',
            component: '',
          },
          {
            ingredientID: 0,
            name: 'Mascarpone',
            lifespanDays: 14,
            purchaseUnit: 'pound',
            gramRatio: 453.59,
            purchaseUnitRatio: 0.0625,
            measurementUnit: 'weightOunce',
            measurement: 16,
            preparation: '',
            component: '',
          },
          {
            ingredientID: 0,
            name: 'Cocoa Powder',
            lifespanDays: 365,
            purchaseUnit: 'pound',
            gramRatio: 453.59,
            purchaseUnitRatio: 0.0021,
            measurementUnit: 'dash',
            measurement: 1,
            preparation: 'for dusting',
            component: '',
          },
          {
            ingredientID: 0,
            name: 'Ladyfinger Cookies',
            lifespanDays: 7,
            purchaseUnit: 'single',
            gramRatio: 7,
            purchaseUnitRatio: 1,
            measurementUnit: 'single',
            measurement: 45,
            preparation: '',
            component: '',
          },
          {
            ingredientID: 0,
            name: 'Heavy Cream',
            lifespanDays: 10,
            purchaseUnit: 'pint',
            gramRatio: 502,
            purchaseUnitRatio: 0.5,
            measurementUnit: 'cup',
            measurement: 2,
            preparation: '',
            component: '',
          },
          {
            ingredientID: 0,
            name: 'Sugar',
            lifespanDays: 999,
            purchaseUnit: 'pound',
            gramRatio: 454,
            purchaseUnitRatio: 0.5,
            measurementUnit: 'cup',
            measurement: 0.5,
            preparation: '',
            component: '',
          },
          {
            ingredientID: 0,
            name: 'Vanilla Extract',
            lifespanDays: 360,
            purchaseUnit: 'fluidOunce',
            gramRatio: 25,
            purchaseUnitRatio: 0.167,
            measurementUnit: 'teaspoon',
            measurement: 0.5,
            preparation: '',
            component: '',
          },
          {
            ingredientID: 0,
            name: 'Salt',
            lifespanDays: 999,
            purchaseUnit: 'weightOunce',
            gramRatio: 28,
            purchaseUnitRatio: 0.17,
            measurementUnit: 'teaspoon',
            measurement: 0.5,
            preparation: '',
            component: '',
          },
          {
            ingredientID: 0,
            name: 'Egg',
            lifespanDays: 30,
            purchaseUnit: 'dozen',
            gramRatio: 600,
            purchaseUnitRatio: 0.825,
            measurementUnit: 'single',
            measurement: 4,
            preparation: '',
            component: '',
          },
        ],
        tools: [
          {
            toolID: 0,
            name: 'Baking Dish 9x13 Inch',
            quantity: 1,
          },
          {
            toolID: 0,
            name: 'Whisk',
            quantity: 1,
          },
          {
            toolID: 0,
            name: 'Stand Mixer',
            quantity: 1,
          },
          {
            toolID: 0,
            name: 'Spatula',
            quantity: 1,
          },
          {
            toolID: 0,
            name: `Chef's Knife 8 Inch`,
            quantity: 1,
          },
          {
            toolID: 0,
            name: 'Strainer',
            quantity: 1,
          },
          {
            toolID: 0,
            name: 'Plastic Wrap Sheet',
            quantity: 1,
          },
          {
            toolID: 0,
            name: 'Aluminum Foil Sheet',
            quantity: 1,
          },
        ],
        steps: [
          {
            stepID: 0,
            title: 'Prepare Baking Pan',
            description: 'You need a large 9x13 inch baking pan/dish with at least a 12-14 cup capacity. Set aside and have ready to go!',
            sequence: 1,
            photoURL: '',
          },
          {
            stepID: 0,
            title: 'Dip Half of the Ladyfingers',
            description: `You will form 2 layers each of dipped ladyfingers and mascarpone cream. Let's begin with the 1st layer of ladyfingers. Whisk the espresso and Grand Marnier together in a shallow bowl. One at a time, quickly dip each side of the ladyfinger into the espresso mixture. You don't want to over-saturate the ladyfinger with liquid because then the ladyfingers will taste soggy. Just a quick dip on each side. Arrange the dipped ladyfingers in the baking pan to make one solid layer. If needed, cut some ladyfingers to fill in any empty spaces. Reserve remaining espresso mixture and ladyfingers for another layer.`,
            sequence: 2,
            photoURL: 'https://s3.us-west-2.amazonaws.com/dl.images/recipeStep/a525810e-5531-4f97-95a4-39a082f7416b/recipeStepImage_1715745786064',
          },
          {
            stepID: 0,
            title: 'Begin the Mascarpone Cream',
            description: `With a handheld or stand mixer fitted with a paddle or whisk attachment, beat the mascarpone and rum together on medium speed in a large bowl until smooth. Set aside.`,
            sequence: 3,
            photoURL: '',
          },
          {
            stepID: 0,
            title: 'Prepare a Double Boiler for the Egg Yolks',
            description: `If you have a double boiler, use it in this step. If you don't, place a heat-proof bowl over a small pot of simmering water over medium-low heat. Don't let the water touch the bottom of the bowl.  Using a whisk or eggbeater (I simply use a whisk), whisk the egg yolks and 1/4 cup (50g) of granulated sugar together until light and foamy, about 5 minutes. Remove from the heat and immediately pour into the mascarpone mixture. Beat on medium speed until combined.`,
            sequence: 4,
            photoURL: '',
          },
          {
            stepID: 0,
            title: 'Whip the Heavy Cream',
            description: `With a handheld or stand mixer fitted with a whisk attachment, beat the heavy cream and vanilla extract together on medium-high speed until medium peaks form, about 3-4 minutes. Medium peaks are between soft/loose peaks and stiff peaks and are the perfect consistency for the tiramisu cream. Fold the whipped cream into the mascarpone mixture.`,
            sequence: 5,
            photoURL: 'https://s3.us-west-2.amazonaws.com/dl.images/recipeStep/a525810e-5531-4f97-95a4-39a082f7416b/recipeStepImage_1715745801988',
          },
          {
            stepID: 0,
            title: 'Beat the Egg Whites',
            description: `With a handheld or stand mixer fitted with a *clean* whisk attachment, beat the egg whites and salt together on medium-high speed until foamy, about 1 minute. Increase to high speed and slowly pour in the remaining 1/4 cup (50g) of sugar. Beat until stiff peaks form, about 4-5 minutes. (Do not over-beat as the egg whites will become dry.) Fold into the mascarpone cream.`,
            sequence: 6,
            photoURL: '',
          },
          {
            stepID: 0,
            title: 'Spread Half of the Mascarpone Cream',
            description: `Spread half of the mascarpone cream evenly over bottom layer of ladyfingers. An offset spatula helps spread it neatly and evenly.`,
            sequence: 7,
            photoURL: 'https://s3.us-west-2.amazonaws.com/dl.images/recipeStep/a525810e-5531-4f97-95a4-39a082f7416b/recipeStepImage_1715745851056',
          },
          {
            stepID: 0,
            title: 'Dip Remaining Ladyfingers',
            description: `Dip remaining ladyfingers into remaining espresso mixture and arrange one-by-one on top of the mascarpone layer. Gently press each down so they are nice and compact. Using an offset spatula, spread remaining mascarpone mixture evenly on top. If you're using a large enough pan, it should all fit (but it will definitely tower high!). Refrigerate uncovered for 2-3 hours.`,
            sequence: 8,
            photoURL: '',
          },
          {
            stepID: 0,
            title: 'Add Cocoa Layer, then Chill',
            description: `After a couple hours in the refrigerator, sift or strain a dense layer of cocoa powder all over the top. Wipe the rim of the baking dish. Cover with plastic wrap or aluminum foil, then refrigerate for at least 8-9 more hours and up to 1 day.`,
            sequence: 9,
            photoURL: '',
          },
          {
            stepID: 0,
            title: 'Slice and Serve',
            description: `Using a sharp knife, slice chilled tiramisu into servings. Wipe knife clean between cuts.`,
            sequence: 10,
            photoURL: '',
          },
        ],
      },
    ],
  },
};

module.exports = {
  initialData,
};
