const recipeCategories = {
  1: 'Other',
  2: 'African',
  3: 'American',
  4: 'Appetizer',
  5: 'Baked Good',
  6: 'Breakfast',
  7: 'Caribbean',
  8: 'Chinese',
  9: 'Dessert',
  10: 'Dinner',
  11: 'East European',
  12: 'French',
  13: 'Gluten Free',
  14: 'Greek',
  15: 'Indian',
  16: 'Italian',
  17: 'Japanese',
  18: 'Korean',
  19: 'Low Carb',
  20: 'Lunch',
  21: 'Mediterranean',
  22: 'Mexican',
  23: 'Middle Eastern',
  24: 'Quick & Easy',
  25: 'Salad',
  26: 'Seafood',
  27: 'Snack',
  28: 'South American',
  29: 'Spanish',
  30: 'Soup',
  31: 'Thai',
  32: 'Vegan',
  33: 'Vegetarian',
  34: 'Vietnamese',
};

module.exports = {
  recipeCategories,
};
