name: AWS Infra Deploy draft

on:
  pull_request:
    branches: [ main ]

jobs:
  - name: Deploy to EC2
    env:
      API_EC2_HOST: ${{ secrets.API_EC2_HOST }}
      SSH_KEY: ${{ secrets.API_SSH_PRIVATE_KEY }}
      DEST_PATH: '/home/ubuntu/dl/'
      APP_NAME: 'doughly'
    run: |
      # Install SSH Client (if not present)
      sudo apt-get update
      sudo apt-get install -y openssh-client

      # Setup SSH Key
      mkdir -p ~/.ssh
      echo "$SSH_KEY" > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa

      # SSH into the EC2 instance and run commands
      ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${API_EC2_HOST} << 'EOF'
        # Stop the server using PM2
        pm2 stop ${APP_NAME} || true  # '|| true' to ignore if the app isn't found

        # Clean the directory
        rm -rf ${DEST_PATH}/*

        # Exit SSH session
      EOF

      # Rsync to EC2
      rsync -avz -e "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=~/.ssh/known_hosts" ./server/ ubuntu@${API_EC2_HOST}:${DEST_PATH}

      # SSH into the EC2 instance to restart the server
      ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${API_EC2_HOST} << 'EOF'
        # Navigate to the directory
        cd ${DEST_PATH}

        # Install dependencies
        npm install

        # Start the server using PM2
        pm2 start app.js --name "${APP_NAME}"  # Replace 'app.js' with your entry file

        # Save the PM2 process list to restart on server reboot
        pm2 save

        # Exit SSH session
      EOF


