name: AWS Infra Deploy

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy-api:
    if: contains(github.event.pull_request.labels.*.name, 'deploy-back-api-production')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH Known Hosts
      env:
        EC2_SSH_FINGERPRINT: ${{ secrets.EC2_SSH_FINGERPRINT }}
      run: |
        mkdir -p ~/.ssh
        echo "$EC2_SSH_FINGERPRINT" >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Copy Server Directory to EC2
      env:
        API_EC2_HOST: ${{secrets.API_EC2_HOST}}  # Your EC2 IP or domain
        SSH_KEY: ${{secrets.API_SSH_PRIVATE_KEY}}  # Your SSH private key
        DEST_PATH: '/home/ubuntu/dl/'  # Destination path on EC2
      run: |
        # Install SSH Client (if not present)
        sudo apt-get update
        sudo apt-get install -y openssh-client

        # Setup SSH Key
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Rsync to EC2
        rsync -avz -e "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=~/.ssh/known_hosts" ./server/ ubuntu@${API_EC2_HOST}:${DEST_PATH}

